###################################################################################################

docker_service_name: docker

###################################################################################################

docker_packages:
  - docker.io

###################################################################################################
