###################################################################################################

docker_package_state    : present
docker_service_enabled  : yes
docker_service_state    : started

###################################################################################################
