###################################################################################################

bridge_network_service_name: networking

###################################################################################################

bridge_packages:
  - bridge-utils

###################################################################################################
