###################################################################################################

- name: debian | docker | check image
  command: docker images --format \{\{.Repository\}\}:\{\{.Tag\}\}
  changed_when: false
  register: etcd_docker_image_check

###################################################################################################

- name: debian | docker | pull image
  command: docker pull '{{ etcd_docker_image }}'
  when: not etcd_docker_image in etcd_docker_image_check.stdout_lines

###################################################################################################

- name: debian | directory | data
  file:
    path  : '{{ etcd_data_directory }}'
    state : directory
    owner : root
    group : root

###################################################################################################

- name: debian | template | etcd.service
  template:
    src   : etcd.service.j2
    dest  : /lib/systemd/system/etcd.service
    owner : root
    group : root
    mode  : 0644
  notify:
    - systemctl daemon-reload
    - restart etcd

###################################################################################################

- name: debian | service
  service:
    name: etcd
    state: started
    enabled: yes

###################################################################################################
