###################################################################################################

kubernetes_repo_key_state : present
kubernetes_repo_state     : present
kubernetes_packages_state : present

###################################################################################################

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

###################################################################################################

kubernetes_config_path  : /etc/kubernetes
kubernetes_pki_path     : '{{ kubernetes_config_path }}/pki'

###################################################################################################

kubernetes_pki_ca_cert_filename : ca.pem
kubernetes_pki_ca_cert          : '{{ kubernetes_pki_path }}/{{ kubernetes_pki_ca_cert_filename }}'

###################################################################################################

kubernetes_master_address: https://192.168.255.10:6443

###################################################################################################
