###################################################################################################

- name: apt_key
  apt_key:
    url   : '{{ kubernetes_repo_key }}'
    state : '{{ kubernetes_repo_key_state }}'

###################################################################################################

- name: apt_repository
  apt_repository:
    repo  : '{{ kubernetes_repo }}'
    state : '{{ kubernetes_repo_state }}'

###################################################################################################

- name: apt
  apt:
    name  : '{{ item }}'
    state : '{{ kubernetes_packages_state }}'
  with_items: '{{ kubernetes_packages }}'

###################################################################################################
