###################################################################################################

- name: template | 99-kubelet.conf
  template:
    src: kubelet/config/99-kubelet.conf.j2
    dest: '{{ kubernetes_kubelet_systemd_config_file }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd
    - kubelet

###################################################################################################

- include_tasks: main.yml

###################################################################################################
