###################################################################################################

- name: template | kubelet.conf
  template:
    src: kubelet/config/kubelet.conf.j2
    dest: '{{ kubernetes_kubelet_config_file }}'
    owner: root
    group: root
    mode: 0600
  notify: kubelet

###################################################################################################

- include_tasks: manifests/main.yml

###################################################################################################
