###################################################################################################

- name: debian | packages
  apt:
    name  : '{{ item }}'
    state : '{{ docker_package_state }}'
  with_items: '{{ docker_packages }}'

###################################################################################################

- name: debian | service
  service:
    name    : '{{ docker_service_name }}'
    enabled : '{{ docker_service_enabled }}'
    state   : '{{ docker_service_state }}'

###################################################################################################
