###################################################################################################

etcd_data_directory: /var/lib/etcd

###################################################################################################
